#!/usr/bin/env bash
#Displays information about subdomains.
# shellcheck disable = SC2086


subdomain_info() {
	subdomain=$1
	domain=".miguelcortes.tech"
	fulldomain=$subdomain$domain
	echo -n "The subdomain $subdomain is a "
	dig $fulldomain | awk '/ANSWER SECTION:/ {getline;print;}' | awk '{print $4 " record and points to " $5}'
}

if [ -z "$2" ]; then
	subdomain_info "www"
	subdomain_info "lb-01"
	subdomain_info "web-01"
	subdomain_info "web-02"
else
	subdomain_info "$2"
fi
