#!/usr/bin/env bash
#Installs Nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | tee /var/www/html/index.nginx-debian.html
sudo service nginx start
