#!/usr/bin/env bash
#Installs Nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
rewrite = "rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $rewrite" /etc/nginx/sites-available/default
sudo service nginx start
