#!/usr/bin/env bash
#Installs nginx web server.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "42i rewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sed -i "50i error_page 404 /custom_404.html; location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;" /etc/nginx/sites-enabled/default
sudo service nginx restart
