#!/usr/bin/env bash
#Installs nginx web server.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "42i rewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "50i error_page 404 /custom_404.html;\n\tlocation /custom_404.html{\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx restart
