#!/usr/bin/env bash
#Installs Nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
rewrite="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $rewrite" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
custom_error="error_page 404 /custom_404.html; \nlocation = /custom_404.html { \nroot /usr/share/nginx/html; \ninternal; }"
sudo sed -i "43i $custom_error" /etc/nginx/sites-available/default
sudo sed -i "28i add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start
