#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install haproxy=2.0.\*
