#!/usr/bin/env bash
#Generates a mysql dump of all databases and creates a compressed archive of it.

sudo mysqldump -u root -p'$1' --all-databases > backup.sql
d=$(date +"%d-%m-%y") 
extension=".tar.gz"
sudo tar -zcf $d$extension backup.sql
