#!/usr/bin/env bash
#Makes server to listen to port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/ ipv6only=on//' /etc/nginx/sites-enabled/default
sudo service nginx restart
