#!/usr/bin/env bash
#Displays numbers from 1 to 100. Exceptions: Fizzbuzz when it's a multiple of 3 and 5, Fizz of 3, Fuzz of five.

for i in {1..100}
do
	if [[ $(( i % 3 )) -eq 0  && $(( i % 5 )) -eq 0 ]]
		then echo "FizzBuzz"
	elif [ $(( i % 3 )) -eq 0 ]
		then echo "Fizz"
	elif [ $(( i % 5 )) -eq 0 ]
		then echo "Buzz"
	else
		echo "$i"
	fi
done
